---
title: "Dissertation Abstract: Temperature Adaptation in Common Forest Ants"
header-includes:
   - \setlength\parindent{24pt}\setlength{\parskip}{0.0pt plus 1.0pt}
output: 
  pdf_document:
    latex_engine: xelatex
mainfont: Times New Roman
---
\large
\makeatletter
\newcommand\iraggedright{%
  \let\\\@centercr\@rightskip\@flushglue \rightskip\@rightskip
  \leftskip\z@skip}
\makeatother
\iraggedright




Temperature is a fundamental environmental force shaping species abundance and distributions through its effects on biochemical reaction rates, metabolism, activity,and reproduction. In light of future climate shifts, mainly driven by temperature increases, how will organisms persist in a variable environment? For example, the cellular stress response (CSR) allow organisms to persist by protecting against macromolecular damage that lead to impaired growth. Molecular chaperones, such as Heat shock proteins (Hsps) are the main drivers of the CSR which participate in preventing and rescuing protein damage, however, we have a poor understanding of the diversity of Hsps in taxonomic groups outside model systems. Ants are a good system to understand the physiological mechanisms to cope with heat stress because they have been able to diversify into thermally stressful environments. 

First, **I identified and characterized the functional diversity of Hsps in ants**. Since many ant genomes were publicly available, I bioinformatically surveyed Hsp orthologues to test for selection and to reconstruct their evolutionary history. At a broad taxonomic level, ants utilize unique sets of Hsps for the CSR and stabilizing selection was the prevailing force among Hsp orthologues, suggesting Hsps harbor conserved protein activity. Meanwhile, regulatory regions (promoter) governing transcriptional up-regulation diversified: ranging in the number, position, and location along their regulatory elements (Heat shock elements, HSE). The presence of HSEs verified their role in the CSR. **Therefore, modulating the tempo of up-regulation may be critical for adaptive variation in the CSR**. 

I hypothesized that ant species modulate the regulation of critical stress proteins (Hsps) to match their local thermal environment. In a common garden, I collected common woodland ants along the Eastern United States to determine **1) the relationship between local thermal evironments and physiological tolerances to temperature** and **2) whether the adaptive variation in thermal tolerances related to the tempo of the CSR**. Despite no evidence for clinal variation in heat tolerance (Critical thermal maxima, CTmax), I found evidence of for the correlated influence of phylogeny and ecology (phylogenetic niche conservatism) on CTmax in common woodland ants such that more heat tolerant ants species lived in open habitats (Mixed-hardwood and deciduous forests) and less heat tolerance lived in closed habitats (Flat woods). These adaptive shifts corresponded with the timing of induction: more thermally tolerant ant species residing in open habitats delayed their Hsp expression, potentially indicating that they are robust to macromolecular purterbations. Furthermore, open habitat species operate closer to their upper thermal limits and may be more susceptible to climate change because warming will push temperatures towards and beyond physiological limits. 

Although temperature is a critical environmental feature of landscapes, it is likely to interact with other environmental factors such as water and nutrient availability that will impact physiological tolerances in complex ways. I determined the influence of hydration and nutrition stress on heat tolerance measured as knock-down time, Under controlled laboratory settings. Those pre-treated with starvation were much less thermally tolerant than controls, and this effect was much more extreme than pre-treatment with desiccant. Since ants are likely to experience these combination of stressors in the wild, current estimates of may be underestimating the effects of future warming. Therefore, future models need to consider multiple axes of environmental change. 

